apply plugin: 'com.android.library'

android {
    compileSdkVersion 37

    defaultConfig {
        minSdkVersion 24
    }
    lint {
        abortOnError = false
    }
    namespace = 'com.simplecityapps.recyclerview_fastscroll'

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //RecyclerView
    implementation libs.androidx.recyclerview

    // AppCompat
    implementation libs.androidx.appcompat
}

//To deploy, re-comment following line & run ./gradlew clean assembleRelease install bintrayUpload
//apply from : 'deploy.gradle'